In [2]:
import matplotlib.pyplot as plt
import numpy as np
import os
import sys
import pandas as pd
import time
import sklearn
import tensorflow as tf

for module in tf, np, sklearn, tf.keras, pd:
    print(module.__name__, module.__version__)


tensorflow 2.0.0
numpy 1.17.4
sklearn 0.20.0
tensorflow_core.keras 2.2.4-tf
pandas 0.25.3


In [2]:
#常量
t = tf.constant([[1., 2., 3.],[4., 5., 6.]])
print(t)
print(t[0,0:2])
print(t[...,1])


tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor([1. 2.], shape=(2,), dtype=float32)
tf.Tensor([2. 5.], shape=(2,), dtype=float32)


In [3]:
#算子操作
print(t + 10)
print(tf.square(t))
print(t @ tf.transpose(t))

tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)


In [4]:
# numpy
print(t.numpy())
print(np.square(t))
np_t = np.array([[1., 2., 3.],[4., 5., 6.]])
print(tf.constant(np_t))

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)


In [5]:
#scaler
t = tf.constant(2.718)
print(t.numpy())
print(t.shape)

2.718
()


In [6]:
# string
t = tf.constant("hello world")
print(t)
print(tf.strings.length(t))
print(tf.strings.length(t, unit='UTF8_CHAR'))
print(tf.strings.unicode_decode(t, "UTF8"))

tf.Tensor(b'hello world', shape=(), dtype=string)
tf.Tensor(11, shape=(), dtype=int32)
tf.Tensor(11, shape=(), dtype=int32)
tf.Tensor([104 101 108 108 111  32 119 111 114 108 100], shape=(11,), dtype=int32)


In [7]:
# string array
t = tf.constant(["cafe", "coffee", "咖啡"])
print(tf.strings.length(t, unit="UTF8_CHAR"))
print(tf.strings.unicode_decode(t, "UTF8"))

tf.Tensor([4 6 2], shape=(3,), dtype=int32)
<tf.RaggedTensor [[99, 97, 102, 101], [99, 111, 102, 102, 101, 101], [21654, 21857]]>


In [8]:
# ragged tensor
t = tf.ragged.constant([[1, 2, 3], [1, 2], [], [41]])
print(t)
print(t[1])
print(t[1:3])
print(t[1,1])

<tf.RaggedTensor [[1, 2, 3], [1, 2], [], [41]]>
tf.Tensor([1 2], shape=(2,), dtype=int32)
<tf.RaggedTensor [[1, 2], []]>
tf.Tensor(2, shape=(), dtype=int32)


In [9]:
# ops on ragged tensor
r = tf.ragged.constant([[51, 52], [], [2], []])
print(tf.concat([t, r], axis=0))
print(tf.concat([r, t], axis=1))

<tf.RaggedTensor [[1, 2, 3], [1, 2], [], [41], [51, 52], [], [2], []]>
<tf.RaggedTensor [[51, 52, 1, 2, 3], [1, 2], [2], [41]]>


In [10]:
# ragged to normal
print(t.to_tensor())

tf.Tensor(
[[ 1  2  3]
 [ 1  2  0]
 [ 0  0  0]
 [41  0  0]], shape=(4, 3), dtype=int32)


In [11]:
# sparse tensor
s = tf.SparseTensor(indices=[[0, 1], [1, 0], [2, 3]], values=[1., 2., 3.], dense_shape=[3, 4])
print(s)
print(tf.sparse.to_dense(s))
s = tf.SparseTensor(indices=[[1, 0], [0, 1], [2, 3]], values=[1., 2., 3.], dense_shape=[3, 4])
s = tf.sparse.reorder(s)
print(tf.sparse.to_dense(s))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[0. 1. 0. 0.]
 [2. 0. 0. 0.]
 [0. 0. 0. 3.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[0. 2. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 3.]], shape=(3, 4), dtype=float32)


In [12]:
# Ops on sparse tensor
s2 = s * 2.0
print(s2)
try:
    s3 = s + 1 
except TypeError as ex:
    print(ex)

s4 = tf.constant([[10., 20.], [30., 40.], [50., 60.], [70., 80.]])
print(tf.sparse.sparse_dense_matmul(s2, s4))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([4. 2. 6.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
unsupported operand type(s) for +: 'SparseTensor' and 'int'
tf.Tensor(
[[120. 160.]
 [ 20.  40.]
 [420. 480.]], shape=(3, 2), dtype=float32)


In [13]:
# 变量
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
print(v.value())
print(v.numpy())

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
[[1. 2. 3.]
 [4. 5. 6.]]


In [15]:
# assign value
v.assign(2 * v)
print(v.numpy())

v[0, 1].assign(3)
print(v.numpy())

v[1].assign([7., 8., 9.])
print(v.numpy())

try:
    v[1] = [7, 8, 9]
except TypeError as ex:
    print(ex)

[[ 4.  6. 12.]
 [14. 16. 18.]]
[[ 4.  3. 12.]
 [14. 16. 18.]]
[[ 4.  3. 12.]
 [ 7.  8.  9.]]
'ResourceVariable' object does not support item assignment


In [ ]:
# 自定义loss_fn
def mse(y, pred):
    return tf.reduce_mean(tf.square(y - pred))

In [ ]:
# 自定义layer

class Customlized_layer(tf.keras.layers.Layer):
    def __init__(self, units, activation=None, **kwargs):
        self.units = units
        self.activation = tf.keras.layers.Activation(activation)
        super(Customlized_layer, self).__init__()
        
    def build(self, input_shape):
        self.kernel = self.add_weight(name='kernel', 
                                      shape=(input_shape[1], self.units),
                                      initializer='uniform',
                                      trainable=True)
        self.bias = self.add_weight(name='bias', 
                                      shape=(self.units, ),
                                      initializer='zeros',
                                      trainable=True)
        super(Customlized_layer, self).build(input_shape)
        
    def call(self, inputs, **kwargs):
        return self.activation(x @ self.kernel + self.bias)
    

In [4]:
# 自定义求导
def g(x1, x2):
    return x1 * 5 + x2 **3

x1 = tf.constant(2.0)
x2 = tf.constant(3.0)
with tf.GradientTape(persistent=True) as tape:
    tape.watch(x1)
    tape.watch(x2)
    z = g(x1, x2)
    
dz_dx1dx2 = tape.gradient(z, [x1, x2])
print(dz_dx1dx2)

[<tf.Tensor: id=22, shape=(), dtype=float32, numpy=5.0>, <tf.Tensor: id=27, shape=(), dtype=float32, numpy=27.0>]
